export const übersetzung = {
    de: {
        index_welcome: "Willkommen bei Blue Ocean Dive",
        index_zitat: '"Tauche ein in die Welt der Unterwasser-Abenteuer!"',
        index_einführungstext: "Tauche ein in eine Welt voller Abenteuer, Entspannung und einzigartiger Entdeckungen. Bei Blue Ocean Dive verbinden wir Leidenschaft für das Meer mit professioneller Ausbildung und individuellen Tauch-Erlebnissen. Ob du deine ersten Atemzüge unter Wasser erleben möchtest oder ein erfahrener Taucher bist, bei uns findest du genau das richtige Angebot. Unsere Tauchschule steht für höchste Sicherheitsstandards, erfahrene und herzliche Tauchlehrer sowie unvergessliche Momente in einer faszinierenden Unterwasserwelt. Zudem liegt uns der Schutz der Meere besonders am Herzen. Gemeinsam setzen wir uns für nachhaltiges Tauchen und den Erhalt unserer Ozeane ein. Willkommen an Bord – entdecke mit uns die Wunder der Tiefsee!",
        index_aktuelles: "AKTUELLES",
        index_naturschutz: "Unser Projekt Naturschutz",
        index_bildung: "Unser Bildungsprojekt",
        index_mehrdazu: "Mehr dazu",
        index_tauchen: "TAUCHEN AUF MALLORCA",
        index_p1: "Erlebe die faszinierende Unterwasserwelt Mallorcas! Die Insel bietet dir nicht nur traumhafte Strände und kristallklares Wasser, sondern auch eine beeindruckende Vielfalt an Tauchrevieren. Von bunten Korallenriffen über geheimnisvolle Höhlen bis hin zu faszinierenden Wracks – Mallorcas Unterwasserwelt hat für Anfänger und erfahrene Taucher gleichermaßen einiges zu bieten.",
        index_p2: "Tauche in kleinen Gruppen an den schönsten Spots der Insel. Entdecke Meeresschildkröten, Zackenbarsche und eine beeindruckende Vielfalt an Fischen, während die Sonne die Wasseroberfläche in ein schimmerndes Lichtspiel verwandelt. Sicherheit, Spaß und nachhaltiges Tauchen stehen dabei immer im Mittelpunkt.",
        index_p3: "Mallorca wartet darauf, von dir entdeckt zu werden – und wir freuen uns, dich dabei zu begleiten! Tauche mit uns ein und erlebe unvergessliche Momente unter der Wasseroberfläche.",
    },
    en: {
        index_welcome: "Welcome to Blue Ocean Dive",
        index_zitat: '"Dive into the world of underwater adventures!"',
        index_einführungstext: "Dive into a world full of adventure, relaxation, and unique discoveries. At Blue Ocean Dive, we combine a passion for the sea with professional training and personalized diving experiences. Whether you're taking your first breaths underwater or you're an experienced diver, you'll find the perfect offer with us. Our diving school stands for the highest safety standards, experienced and friendly instructors, and unforgettable moments in a fascinating underwater world. We also deeply care about protecting the oceans. Together, we are committed to sustainable diving and preserving our marine ecosystems. Welcome aboard – discover the wonders of the deep sea with us!",
        index_aktuelles: "NEWS",
        index_naturschutz: "Our Conservation Project",
        index_bildung: "Our Educational Project",
        index_mehrdazu: "Learn more",
        index_tauchen: "DIVING IN MALLORCA",
        index_p1: "Experience the fascinating underwater world of Mallorca! The island not only offers you stunning beaches and crystal-clear waters, but also an impressive variety of dive sites. From colorful coral reefs and mysterious caves to fascinating wrecks – Mallorca’s underwater world has something to offer for both beginners and experienced divers alike.",
        index_p2: "Dive in small groups at the most beautiful spots on the island. Discover sea turtles, groupers, and an impressive variety of fish as the sun transforms the water’s surface into a shimmering play of light. Safety, fun, and sustainable diving are always at the heart of the experience.",
        index_p3: "Mallorca is waiting to be discovered by you – and we’re excited to be part of your journey! Dive in with us and experience unforgettable moments beneath the surface.",
    },
    es: {
        index_welcome: "Bienvenido a Blue Ocean Dive",
        index_zitat: '"¡Sumérgete en el mundo de las aventuras submarinas!"',
        index_einführungstext: "Sumérgete en un mundo lleno de aventuras, relajación y descubrimientos únicos. En Blue Ocean Dive, combinamos la pasión por el mar con formación profesional y experiencias de buceo personalizadas. Tanto si quieres dar tus primeras respiraciones bajo el agua como si ya eres un buceador experimentado, con nosotros encontrarás la oferta perfecta. Nuestra escuela de buceo representa los más altos estándares de seguridad, instructores experimentados y amables, y momentos inolvidables en un mundo submarino fascinante. Además, la protección de los océanos es una prioridad para nosotros. Juntos, apostamos por un buceo sostenible y la conservación de nuestros mares. ¡Bienvenido a bordo – descubre con nosotros las maravillas de las profundidades marinas!",
        index_aktuelles: "ACTUALIDAD",
        index_naturschutz: "Nuestro proyecto de conservación",
        index_bildung: "Nuestro proyecto educativo",
        index_mehrdazu: "Más información",
        index_tauchen: "BUCEO EN MALLORCA",
        index_p1: "¡Descubre el fascinante mundo submarino de Mallorca! La isla no solo te ofrece playas de ensueño y aguas cristalinas, sino también una impresionante variedad de zonas de buceo. Desde coloridos arrecifes de coral y misteriosas cuevas hasta fascinantes naufragios: el mundo submarino de Mallorca tiene mucho que ofrecer tanto a principiantes como a buceadores experimentados.",
        index_p2: "Bucea en pequeños grupos en los lugares más hermosos de la isla. Descubre tortugas marinas, meros y una impresionante variedad de peces, mientras el sol convierte la superficie del agua en un juego de luces resplandeciente. La seguridad, la diversión y el buceo sostenible siempre están en el centro de la experiencia.",
        index_p3: "Mallorca está esperando a ser descubierta por ti – ¡y estamos encantados de acompañarte en esta aventura! Sumérgete con nosotros y vive momentos inolvidables bajo la superficie del agua.",
    }
};